import type { Spell } from '@fablesheet/core'

export const SPELL_CATALOG: Spell[] = [
  // ── Cantrips (Level 0) ──────────────────────────────────────────────────────
  {
    id: 'chill-touch', name: 'Chill Touch', level: 0, school: 'Necromancy',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: '1 round', concentration: false, ritual: false,
    description: 'You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can\'t regain hit points until the start of your next turn.',
    higherLevels: null,
  },
  {
    id: 'mage-hand', name: 'Mage Hand', level: 0, school: 'Conjuration',
    castingTime: '1 Action', range: '30 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: '1 minute', concentration: false, ritual: false,
    description: 'A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item, or pour the contents out of a vial.',
    higherLevels: null,
  },
  {
    id: 'shocking-grasp', name: 'Shocking Grasp', level: 0, school: 'Evocation',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack. You have advantage on the roll if the target is wearing metal armor. On a hit, the target takes 1d8 lightning damage and can\'t take reactions until the start of its next turn.',
    higherLevels: null,
  },
  {
    id: 'prestidigitation', name: 'Prestidigitation', level: 0, school: 'Transmutation',
    castingTime: '1 Action', range: '10 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Up to 1 hour', concentration: false, ritual: false,
    description: 'A minor magical trick for novice spellcasters. Create a harmless sensory effect; light or snuff a candle; clean or soil an object; chill, warm, or flavor material; make a color or symbol appear; or create a small nonmagical trinket that lasts until the end of your next turn.',
    higherLevels: null,
  },
  {
    id: 'sacred-flame', name: 'Sacred Flame', level: 0, school: 'Evocation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Flame-like radiance descends on a creature you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.',
    higherLevels: null,
  },
  {
    id: 'light', name: 'Light', level: 0, school: 'Evocation',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: false, material: 'A firefly or phosphorescent moss' },
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You touch one object no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet.',
    higherLevels: null,
  },
  {
    id: 'fire-bolt', name: 'Fire Bolt', level: 0, school: 'Evocation',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn\'t being worn or carried.',
    higherLevels: null,
  },
  {
    id: 'ray-of-frost', name: 'Ray of Frost', level: 0, school: 'Evocation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn.',
    higherLevels: null,
  },
  {
    id: 'vicious-mockery', name: 'Vicious Mockery', level: 0, school: 'Enchantment',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you (though it need not understand you), it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.',
    higherLevels: null,
  },
  {
    id: 'minor-illusion', name: 'Minor Illusion', level: 0, school: 'Illusion',
    castingTime: '1 Action', range: '30 feet',
    components: { verbal: false, somatic: true, material: 'A bit of fleece' },
    duration: '1 minute', concentration: false, ritual: false,
    description: 'You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again. If you create a sound, its volume can range from a whisper to a scream. If you create an image of an object, it must fit within a 5-foot cube.',
    higherLevels: null,
  },
  {
    id: 'guidance', name: 'Guidance', level: 0, school: 'Divination',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.',
    higherLevels: null,
  },
  {
    id: 'thaumaturgy', name: 'Thaumaturgy', level: 0, school: 'Transmutation',
    castingTime: '1 Action', range: '30 feet',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Up to 1 minute', concentration: false, ritual: false,
    description: 'You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range: your voice booms up to three times as loud as normal; you cause flames to flicker, brighten, dim, or change color; you cause harmless tremors in the ground; you create an instantaneous sound; you instantly cause an unlocked door or window to fly open or slam shut; or you alter the appearance of your eyes.',
    higherLevels: null,
  },
  {
    id: 'spare-the-dying', name: 'Spare the Dying', level: 0, school: 'Necromancy',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You touch a living creature that has 0 hit points. The creature becomes stable. This spell has no effect on undead or constructs.',
    higherLevels: null,
  },
  {
    id: 'resistance', name: 'Resistance', level: 0, school: 'Abjuration',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'A miniature cloak' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice. It can roll the die before or after making the saving throw. The spell then ends.',
    higherLevels: null,
  },
  {
    id: 'eldritch-blast', name: 'Eldritch Blast', level: 0, school: 'Evocation',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage. The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level. You can direct the beams at the same target or at different ones.',
    higherLevels: null,
  },
  {
    id: 'true-strike', name: 'True Strike', level: 0, school: 'Divination',
    castingTime: '1 Action', range: '30 feet',
    components: { verbal: false, somatic: true, material: null },
    duration: 'Concentration, up to 1 round', concentration: true, ritual: false,
    description: 'You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target\'s defenses. On your next turn, you gain advantage on your first attack roll against the target, provided that this spell hasn\'t ended.',
    higherLevels: null,
  },
  {
    id: 'poison-spray', name: 'Poison Spray', level: 0, school: 'Conjuration',
    castingTime: '1 Action', range: '10 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm. The creature must succeed on a Constitution saving throw or take 1d12 poison damage.',
    higherLevels: null,
  },

  // ── 1st Level ────────────────────────────────────────────────────────────────
  {
    id: 'burning-hands', name: 'Burning Hands', level: 1, school: 'Evocation',
    castingTime: '1 Action', range: 'Self (15-foot cone)',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A thin sheet of flames shoots from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half on a success. The fire ignites any flammable objects in the area that aren\'t being worn or carried.',
    higherLevels: 'When you cast this spell using a slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
  },
  {
    id: 'detect-magic', name: 'Detect Magic', level: 1, school: 'Divination',
    castingTime: '1 Action', range: 'Self',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: true,
    description: 'For the duration, you sense the presence of magic within 30 feet of you. If you sense magic, you can use your action to see a faint aura around any visible creature or object that bears magic, and learn its school of magic, if any.',
    higherLevels: null,
  },
  {
    id: 'mage-armor', name: 'Mage Armor', level: 1, school: 'Abjuration',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'A piece of cured leather' },
    duration: '8 hours', concentration: false, ritual: false,
    description: 'You touch a willing creature who isn\'t wearing armor, and a protective magical force surrounds it until the spell ends. The target\'s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss it as an action.',
    higherLevels: null,
  },
  {
    id: 'sleep', name: 'Sleep', level: 1, school: 'Enchantment',
    castingTime: '1 Action', range: '90 feet',
    components: { verbal: true, somatic: true, material: 'A pinch of fine sand, rose petals, or a cricket' },
    duration: '1 minute', concentration: false, ritual: false,
    description: 'This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose are affected in ascending order of their current hit points, falling unconscious until the spell ends, they take damage, or someone wakes them.',
    higherLevels: 'When you cast this spell using a slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.',
  },
  {
    id: 'magic-missile', name: 'Magic Missile', level: 1, school: 'Evocation',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously.',
    higherLevels: 'When you cast this spell using a slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.',
  },
  {
    id: 'cure-wounds', name: 'Cure Wounds', level: 1, school: 'Evocation',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'When you cast this spell using a slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.',
  },
  {
    id: 'bless', name: 'Bless', level: 1, school: 'Enchantment',
    castingTime: '1 Action', range: '30 feet',
    components: { verbal: true, somatic: true, material: 'A sprinkling of holy water' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or saving throw before the spell ends, the target can roll a d4 and add the number to the roll.',
    higherLevels: 'When you cast this spell using a slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
  },
  {
    id: 'guiding-bolt', name: 'Guiding Bolt', level: 1, school: 'Evocation',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: '1 round', concentration: false, ritual: false,
    description: 'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes 4d6 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage.',
    higherLevels: 'When you cast this spell using a slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
  },
  {
    id: 'healing-word', name: 'Healing Word', level: 1, school: 'Evocation',
    castingTime: '1 Bonus Action', range: '60 feet',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'When you cast this spell using a slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.',
  },
  {
    id: 'shield', name: 'Shield', level: 1, school: 'Abjuration',
    castingTime: '1 Reaction', range: 'Self',
    components: { verbal: true, somatic: true, material: null },
    duration: '1 round', concentration: false, ritual: false,
    description: 'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.',
    higherLevels: null,
  },
  {
    id: 'thunderwave', name: 'Thunderwave', level: 1, school: 'Evocation',
    castingTime: '1 Action', range: 'Self (15-foot cube)',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn\'t pushed.',
    higherLevels: 'When you cast this spell using a slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
  },
  {
    id: 'faerie-fire', name: 'Faerie Fire', level: 1, school: 'Evocation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed dim light in a 10-foot radius. Any attack roll against an affected creature or object has advantage if the attacker can see it, and the affected creature or object can\'t benefit from being invisible.',
    higherLevels: null,
  },
  {
    id: 'fog-cloud', name: 'Fog Cloud', level: 1, school: 'Conjuration',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You create a 20-foot-radius sphere of fog centered on a point within range. The sphere spreads around corners, and its area is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.',
    higherLevels: 'When you cast this spell using a slot of 2nd level or higher, the radius of the fog increases by 20 feet for each slot level above 1st.',
  },
  {
    id: 'heroism', name: 'Heroism', level: 1, school: 'Enchantment',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A willing creature you touch is imbued with bravery. Until the spell ends, the creature is immune to being frightened and gains temporary hit points equal to your spellcasting ability modifier at the start of each of its turns. When the spell ends, the target loses any remaining temporary hit points from this spell.',
    higherLevels: 'When you cast this spell using a slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
  },
  {
    id: 'hunters-mark', name: "Hunter's Mark", level: 1, school: 'Divination',
    castingTime: '1 Bonus Action', range: '90 feet',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration on the spell for up to 24 hours.',
  },
  {
    id: 'identify', name: 'Identify', level: 1, school: 'Divination',
    castingTime: '1 minute', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'A pearl worth at least 100 gp and an owl feather' },
    duration: 'Instantaneous', concentration: false, ritual: true,
    description: 'You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them, whether it requires attunement to use, and how many charges it has, if any. You learn whether any spells are affecting the item and what they are. If the item was created by a spell, you learn which spell created it.',
    higherLevels: null,
  },
  {
    id: 'longstrider', name: 'Longstrider', level: 1, school: 'Transmutation',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'A pinch of dirt' },
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You touch a creature. The target\'s speed increases by 10 feet until the spell ends.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
  },
  {
    id: 'find-familiar', name: 'Find Familiar', level: 1, school: 'Conjuration',
    castingTime: '1 hour', range: '10 feet',
    components: { verbal: true, somatic: true, material: '10 gp worth of charcoal, incense, and herbs that must be consumed by fire in a brass brazier' },
    duration: 'Instantaneous', concentration: false, ritual: true,
    description: 'You gain the service of a familiar, a spirit that takes an animal form you choose: bat, cat, crab, frog, hawk, lizard, octopus, owl, poisonous snake, fish, rat, raven, seahorse, spider, or weasel. Appearing in an unoccupied space within range, the familiar has the statistics of the chosen form, though it is a celestial, fey, or fiend (your choice) instead of a beast.',
    higherLevels: null,
  },
  {
    id: 'speak-with-animals', name: 'Speak with Animals', level: 1, school: 'Divination',
    castingTime: '1 Action', range: 'Self',
    components: { verbal: true, somatic: true, material: null },
    duration: '10 minutes', concentration: false, ritual: true,
    description: 'You gain the ability to comprehend and verbally communicate with beasts for the duration. The knowledge and awareness of many beasts is limited by their intelligence, but at minimum, beasts can give you information about nearby locations and monsters, including whatever they can perceive or have perceived within the past day.',
    higherLevels: null,
  },

  // ── 2nd Level ────────────────────────────────────────────────────────────────
  {
    id: 'misty-step', name: 'Misty Step', level: 2, school: 'Conjuration',
    castingTime: '1 Bonus Action', range: 'Self',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
    higherLevels: null,
  },
  {
    id: 'hold-person', name: 'Hold Person', level: 2, school: 'Enchantment',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: 'A small, straight piece of iron' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd.',
  },
  {
    id: 'mirror-image', name: 'Mirror Image', level: 2, school: 'Illusion',
    castingTime: '1 Action', range: 'Self',
    components: { verbal: true, somatic: true, material: null },
    duration: '1 minute', concentration: false, ritual: false,
    description: 'Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you and mimic your actions, shifting position so it\'s impossible to track which image is real. You can use your action to dismiss the illusory duplicates. Each time a creature targets you with an attack during the spell\'s duration, roll a d20 to determine whether the attack instead targets one of your duplicates.',
    higherLevels: null,
  },
  {
    id: 'invisibility', name: 'Invisibility', level: 2, school: 'Illusion',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'An eyelash encased in gum arabic' },
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person. The spell ends for a target that attacks or casts a spell.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.',
  },
  {
    id: 'shatter', name: 'Shatter', level: 2, school: 'Evocation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: 'A chip of mica' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw. A creature takes 3d8 thunder damage on a failed save, or half as much damage on a successful one. A creature made of inorganic material such as stone, crystal, or metal has disadvantage on this saving throw.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.',
  },
  {
    id: 'spiritual-weapon', name: 'Spiritual Weapon', level: 2, school: 'Evocation',
    castingTime: '1 Bonus Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: '1 minute', concentration: false, ritual: false,
    description: 'You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes force damage equal to 1d8 + your spellcasting ability modifier. As a bonus action on your turn, you can move the weapon up to 20 feet and repeat the attack against a creature within 5 feet of it.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for every two slot levels above 2nd.',
  },
  {
    id: 'scorching-ray', name: 'Scorching Ray', level: 2, school: 'Evocation',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.',
  },
  {
    id: 'silence', name: 'Silence', level: 2, school: 'Illusion',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: true,
    description: 'For the duration, no sound can be created within or pass through a 20-foot-radius sphere centered on a point you choose within range. Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it. Casting a spell that includes a verbal component is impossible there.',
    higherLevels: null,
  },
  {
    id: 'web', name: 'Web', level: 2, school: 'Conjuration',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: 'A bit of spiderweb' },
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-foot cube from that point for the duration. The webs are difficult terrain and lightly obscure their area. If the webs aren\'t anchored between two solid masses or layered across a floor, wall, or ceiling, the conjured web collapses on itself, and the spell ends at the start of your next turn. Creatures that start their turn in the webs or that enter them during their turn must make a Dexterity saving throw. On a failed save, the creature is restrained as long as it remains in the webs or until it breaks free.',
    higherLevels: null,
  },
  {
    id: 'blur', name: 'Blur', level: 2, school: 'Illusion',
    castingTime: '1 Action', range: 'Self',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Your body becomes blurred, shifting and wavering to all who can see you. For the duration, any creature has disadvantage on attack rolls against you. An attacker is immune to this effect if it doesn\'t rely on sight, as with blindsight, or can see through illusions, as with truesight.',
    higherLevels: null,
  },
  {
    id: 'darkness', name: 'Darkness', level: 2, school: 'Evocation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: false, material: 'Bat fur and a drop of pitch or piece of coal' },
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'Magical darkness spreads from a point you choose within range to fill a 15-foot-radius sphere for the duration. The darkness spreads around corners. A creature with darkvision can\'t see through this magical darkness, and nonmagical light can\'t illuminate it.',
    higherLevels: null,
  },
  {
    id: 'aid', name: 'Aid', level: 2, school: 'Abjuration',
    castingTime: '1 Action', range: '30 feet',
    components: { verbal: true, somatic: true, material: 'A tiny strip of white cloth' },
    duration: '8 hours', concentration: false, ritual: false,
    description: 'Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target\'s hit point maximum and current hit points increase by 5 for the duration.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, a target\'s hit points increase by an additional 5 for each slot level above 2nd.',
  },
  {
    id: 'lesser-restoration', name: 'Lesser Restoration', level: 2, school: 'Abjuration',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You touch a creature and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.',
    higherLevels: null,
  },
  {
    id: 'moonbeam', name: 'Moonbeam', level: 2, school: 'Evocation',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: 'Several seeds of any moonseed plant and a piece of opalescent feldspar' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder centered on a point within range. Until the spell ends, dim light fills the cylinder. When a creature enters the spell\'s area for the first time on a turn or starts its turn there, it is engulfed in ghostly flames that cause searing pain, and it must make a Constitution saving throw. It takes 2d10 radiant damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d10 for each slot level above 2nd.',
  },
  {
    id: 'pass-without-trace', name: 'Pass Without Trace', level: 2, school: 'Abjuration',
    castingTime: '1 Action', range: 'Self',
    components: { verbal: true, somatic: true, material: 'Ashes from a burned leaf of mistletoe and a sprig of spruce' },
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'A veil of shadows and silence radiates from you, masking you and your companions from detection. For the duration, each creature you choose within 30 feet of you (including you) has a +10 bonus to Dexterity (Stealth) checks and can\'t be tracked except by magical means. A creature that receives this bonus leaves behind no tracks or other traces of its passage.',
    higherLevels: null,
  },
  {
    id: 'suggestion', name: 'Suggestion', level: 2, school: 'Enchantment',
    castingTime: '1 Action', range: '30 feet',
    components: { verbal: true, somatic: false, material: 'A snake\'s tongue and either a bit of honeycomb or a drop of sweet oil' },
    duration: 'Concentration, up to 8 hours', concentration: true, ritual: false,
    description: 'You suggest a course of activity (limited to a sentence or two) and magically influence a creature you can see within range that can hear and understand you. The suggestion must be worded in such a manner as to make it sound reasonable. Creatures that can\'t be charmed are immune to this effect. The suggested course of action can continue for the entire duration.',
    higherLevels: null,
  },
  {
    id: 'enthrall', name: 'Enthrall', level: 2, school: 'Enchantment',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: '1 minute', concentration: false, ritual: false,
    description: 'You weave a distracting string of words, causing creatures of your choice that you can see within range and that can hear you to make a Wisdom saving throw. Any creature that can\'t be charmed succeeds on this saving throw automatically, and if you or your companions are fighting a creature, it has advantage on the save. On a failed save, the target has disadvantage on Wisdom (Perception) checks made to perceive any creature other than you until the spell ends or until the target can no longer hear you.',
    higherLevels: null,
  },

  // ── 3rd Level ────────────────────────────────────────────────────────────────
  {
    id: 'fireball', name: 'Fireball', level: 3, school: 'Evocation',
    castingTime: '1 Action', range: '150 feet',
    components: { verbal: true, somatic: true, material: 'A tiny ball of bat guano and sulfur' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
  },
  {
    id: 'lightning-bolt', name: 'Lightning Bolt', level: 3, school: 'Evocation',
    castingTime: '1 Action', range: 'Self (100-foot line)',
    components: { verbal: true, somatic: true, material: 'A bit of fur and a rod of amber, crystal, or glass' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
  },
  {
    id: 'counterspell', name: 'Counterspell', level: 3, school: 'Abjuration',
    castingTime: '1 Reaction', range: '60 feet',
    components: { verbal: false, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell\'s level. On a success, the creature\'s spell fails and has no effect.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.',
  },
  {
    id: 'dispel-magic', name: 'Dispel Magic', level: 3, school: 'Abjuration',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Choose any creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability. The DC equals 10 + the spell\'s level. On a successful check, the spell ends.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you automatically end the effects of a spell on the target if the spell\'s level is equal to or less than the level of the spell slot you used.',
  },
  {
    id: 'fly', name: 'Fly', level: 3, school: 'Transmutation',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'A wing feather from any bird' },
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You touch a willing creature. The target gains a flying speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft, unless it can stop the fall.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you can target one additional creature for each slot level above 3rd.',
  },
  {
    id: 'haste', name: 'Haste', level: 3, school: 'Transmutation',
    castingTime: '1 Action', range: '30 feet',
    components: { verbal: true, somatic: true, material: 'A shaving of licorice root' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Choose a willing creature that you can see within range. Until the spell ends, the target\'s speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns. That action can be used only to take the Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object action. When the spell ends, the target can\'t move or take actions until after its next turn.',
    higherLevels: null,
  },
  {
    id: 'hypnotic-pattern', name: 'Hypnotic Pattern', level: 3, school: 'Illusion',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: false, somatic: true, material: 'A glowing stick of incense or a crystal vial filled with phosphorescent material' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You create a twisting pattern of colors that weaves through the air inside a 30-foot cube within range. The pattern appears for a moment and vanishes. Each creature in the area who sees the pattern must make a Wisdom saving throw. On a failed save, the creature becomes charmed for the duration. While charmed by this spell, the creature is incapacitated and has a speed of 0.',
    higherLevels: null,
  },
  {
    id: 'spirit-guardians', name: 'Spirit Guardians', level: 3, school: 'Conjuration',
    castingTime: '1 Action', range: 'Self (15-foot radius)',
    components: { verbal: true, somatic: true, material: 'A holy symbol' },
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You call forth spirits to protect you. They flit around you to a distance of 15 feet for the duration. If you are good or neutral, their spectral form appears angelic or fey (your choice). If you are evil, they appear fiendish. When you cast this spell, you can designate any number of creatures you can see to be unaffected by it. An affected creature\'s speed is halved in the area, and when the creature enters the area for the first time on a turn or starts its turn there, it must make a Wisdom saving throw. On a failed save, the creature takes 3d8 radiant damage (if you are good or neutral) or 3d8 necrotic damage (if you are evil). On a successful save, the creature takes half as much damage.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d8 for each slot level above 3rd.',
  },
  {
    id: 'mass-healing-word', name: 'Mass Healing Word', level: 3, school: 'Evocation',
    castingTime: '1 Bonus Action', range: '60 feet',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'As you call out words of restoration, up to six creatures of your choice that you can see within range regain hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the healing increases by 1d4 for each slot level above 3rd.',
  },
  {
    id: 'call-lightning', name: 'Call Lightning', level: 3, school: 'Conjuration',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'A storm cloud appears in the shape of a cylinder that is 10 feet tall with a 60-foot radius, centered on a point you can see within range directly above you. The spell fails if you can\'t see a point in the air where the storm cloud could appear. When you cast the spell, choose a point you can see under the cloud. A bolt of lightning flashes down from the cloud to that point. Each creature within 5 feet of that point must make a Dexterity saving throw. A creature takes 3d10 lightning damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 4th or higher level, the damage increases by 1d10 for each slot level above 3rd.',
  },
  {
    id: 'animate-dead', name: 'Animate Dead', level: 3, school: 'Necromancy',
    castingTime: '1 minute', range: '10 feet',
    components: { verbal: true, somatic: true, material: 'A drop of blood, a piece of flesh, and a pinch of bone dust' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature. The target becomes a skeleton if you chose bones or a zombie if you chose a corpse. On each of your turns, you can use a bonus action to mentally command any creature you made with this spell if the creature is within 60 feet of you.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you animate or reassert control over two additional undead creatures for each slot level above 3rd.',
  },
  {
    id: 'bestow-curse', name: 'Bestow Curse', level: 3, school: 'Necromancy',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You touch a creature, and that creature must succeed on a Wisdom saving throw or become cursed for the duration of the spell. When you cast this spell, choose the nature of the curse: disadvantage on ability checks and saving throws of a chosen ability score; disadvantage on attack rolls against you; must make a Wisdom saving throw at the start of each turn or waste action doing nothing; or take an extra 1d8 necrotic damage from your attacks.',
    higherLevels: 'If you cast this spell using a spell slot of 4th level or higher, the duration is concentration, up to 10 minutes. If you use a spell slot of 5th level or higher, the duration is 8 hours. If you use a spell slot of 7th level or higher, the duration is 24 hours. If you use a 9th level spell slot, the spell lasts until it is dispelled.',
  },
  {
    id: 'stinking-cloud', name: 'Stinking Cloud', level: 3, school: 'Conjuration',
    castingTime: '1 Action', range: '90 feet',
    components: { verbal: true, somatic: true, material: 'A rotten egg or several skunk cabbage leaves' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You create a 20-foot-radius sphere of yellow, nauseating gas centered on a point within range. The cloud spreads around corners, and its area is heavily obscured. The cloud lingers in the air for the duration. Each creature that is completely within the cloud at the start of its turn must make a Constitution saving throw against poison. On a failed save, the creature spends its action that turn retching and reeling.',
    higherLevels: null,
  },
  {
    id: 'fear', name: 'Fear', level: 3, school: 'Illusion',
    castingTime: '1 Action', range: 'Self (30-foot cone)',
    components: { verbal: true, somatic: true, material: 'A white feather or the heart of a hen' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You project a phantasmal image of a creature\'s worst fears. Each creature in a 30-foot cone must succeed on a Wisdom saving throw or drop whatever it is holding and become frightened for the duration. While frightened by this spell, a creature must take the Dash action and move away from you by the safest available route on each of its turns, unless there is nowhere to move.',
    higherLevels: null,
  },

  // ── 4th Level ────────────────────────────────────────────────────────────────
  {
    id: 'banishment', name: 'Banishment', level: 4, school: 'Abjuration',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: 'An item distasteful to the target' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to the plane of existence you\'re on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.',
  },
  {
    id: 'dimension-door', name: 'Dimension Door', level: 4, school: 'Conjuration',
    castingTime: '1 Action', range: '500 feet',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction. You can bring along objects as long as their weight doesn\'t exceed what you can carry. You can also bring one willing creature of your size or smaller who is carrying gear up to its carrying capacity.',
    higherLevels: null,
  },
  {
    id: 'ice-storm', name: 'Ice Storm', level: 4, school: 'Evocation',
    castingTime: '1 Action', range: '300 feet',
    components: { verbal: true, somatic: true, material: 'A pinch of dust and a few drops of water' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder centered on a point within range. Each creature in the cylinder must make a Dexterity saving throw. A creature takes 2d8 bludgeoning damage and 4d6 cold damage on a failed save, or half as much damage on a successful one. Hailstones turn the storm\'s area of effect into difficult terrain until the end of your next turn.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the bludgeoning damage increases by 1d8 for each slot level above 4th.',
  },
  {
    id: 'polymorph', name: 'Polymorph', level: 4, school: 'Transmutation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: 'A caterpillar cocoon' },
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. The spell has no effect on a shapechanger or a creature with 0 hit points. The transformation lasts for the duration, or until the target drops to 0 hit points or dies. The new form can be any beast whose challenge rating is equal to or less than the target\'s.',
    higherLevels: null,
  },
  {
    id: 'greater-invisibility', name: 'Greater Invisibility', level: 4, school: 'Illusion',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person. Unlike the invisibility spell, the spell doesn\'t end when the target attacks or casts a spell.',
    higherLevels: null,
  },
  {
    id: 'wall-of-fire', name: 'Wall of Fire', level: 4, school: 'Evocation',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: 'A small piece of phosphorus' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You create a wall of fire on a solid surface within range. The wall can be up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick. The wall is opaque and lasts for the duration. When the wall appears, each creature within its area must make a Dexterity saving throw. On a failed save, a creature takes 5d8 fire damage, or half as much damage on a successful save.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.',
  },
  {
    id: 'confusion', name: 'Confusion', level: 4, school: 'Enchantment',
    castingTime: '1 Action', range: '90 feet',
    components: { verbal: true, somatic: true, material: 'Three nut shells' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'This spell assaults and twists creatures\' minds, spawning delusions and provoking uncontrolled action. Each creature in a 10-foot-radius sphere centered on a point you choose within range must succeed on a Wisdom saving throw when you cast this spell or be affected by it. An affected target can\'t take reactions and must roll a d10 at the start of each of its turns to determine its behavior for that turn.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the radius of the sphere increases by 5 feet for each slot level above 4th.',
  },
  {
    id: 'blight', name: 'Blight', level: 4, school: 'Necromancy',
    castingTime: '1 Action', range: '30 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Necromantic energy washes over a creature of your choice that you can see within range, draining moisture and vitality from it. The target must make a Constitution saving throw. The target takes 8d8 necrotic damage on a failed save, or half as much damage on a successful one. This spell has no effect on undead or constructs.',
    higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.',
  },
  {
    id: 'death-ward', name: 'Death Ward', level: 4, school: 'Abjuration',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: null },
    duration: '8 hours', concentration: false, ritual: false,
    description: 'You touch a creature and grant it a measure of protection from death. The first time the target would drop to 0 hit points as a result of taking damage, the target instead drops to 1 hit point, and the spell ends. If the spell is still in effect when the target is subjected to an effect that would kill it instantaneously without dealing damage, that effect is instead negated against the target, and the spell ends.',
    higherLevels: null,
  },
  {
    id: 'stone-skin', name: 'Stoneskin', level: 4, school: 'Transmutation',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'Diamond dust worth 100 gp, which the spell consumes' },
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'This spell turns the flesh of a willing creature you touch as hard as stone. Until the spell ends, the target has resistance to nonmagical bludgeoning, piercing, and slashing damage.',
    higherLevels: null,
  },

  // ── 5th Level ────────────────────────────────────────────────────────────────
  {
    id: 'cone-of-cold', name: 'Cone of Cold', level: 5, school: 'Evocation',
    castingTime: '1 Action', range: 'Self (60-foot cone)',
    components: { verbal: true, somatic: true, material: 'A small crystal or glass cone' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw. A creature takes 8d8 cold damage on a failed save, or half as much damage on a successful one. A creature killed by this spell becomes a frozen statue until it thaws.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
  },
  {
    id: 'hold-monster', name: 'Hold Monster', level: 5, school: 'Enchantment',
    castingTime: '1 Action', range: '90 feet',
    components: { verbal: true, somatic: true, material: 'A small, straight piece of iron' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. This spell has no effect on undead. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, you can target one additional creature for each slot level above 5th.',
  },
  {
    id: 'flame-strike', name: 'Flame Strike', level: 5, school: 'Evocation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: 'Pinch of sulfur' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A vertical column of divine fire roars down from the heavens in a location you specify. Each creature in a 10-foot-radius, 40-foot-high cylinder centered on a point within range must make a Dexterity saving throw. A creature takes 4d6 fire damage and 4d6 radiant damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the fire damage or the radiant damage (your choice) increases by 1d6 for each slot level above 5th.',
  },
  {
    id: 'mass-cure-wounds', name: 'Mass Cure Wounds', level: 5, school: 'Evocation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point. Each target regains hit points equal to 3d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the healing increases by 1d8 for each slot level above 5th.',
  },
  {
    id: 'telekinesis', name: 'Telekinesis', level: 5, school: 'Transmutation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 10 minutes', concentration: true, ritual: false,
    description: 'You gain the ability to move or manipulate creatures or objects by thought. When you cast the spell, and as your action each round for the duration, you can exert your will on one creature or object that you can see within range, causing the appropriate effect below. You can affect the same target round after round, or choose a new one at any time. If you switch targets, the prior target is no longer affected by the spell.',
    higherLevels: null,
  },
  {
    id: 'dominate-person', name: 'Dominate Person', level: 5, school: 'Enchantment',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You attempt to beguile a humanoid that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. While the creature is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey.',
    higherLevels: 'When you cast this spell using a 6th-level spell slot, the duration is concentration, up to 10 minutes. When you use a 7th-level spell slot, the duration is concentration, up to 1 hour. When you use a spell slot of 8th level or higher, the duration is concentration, up to 8 hours.',
  },
  {
    id: 'animate-objects', name: 'Animate Objects', level: 5, school: 'Transmutation',
    castingTime: '1 Action', range: '120 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, Large targets count as four objects, Huge targets count as eight objects. You can\'t animate any object larger than Huge. Each target animates and becomes a creature under your control until the spell ends or until reduced to 0 hit points.',
    higherLevels: 'If you cast this spell using a spell slot of 6th level or higher, you can animate two additional objects for each slot level above 5th.',
  },

  // ── 6th Level ────────────────────────────────────────────────────────────────
  {
    id: 'chain-lightning', name: 'Chain Lightning', level: 6, school: 'Evocation',
    castingTime: '1 Action', range: '150 feet',
    components: { verbal: true, somatic: true, material: 'A bit of fur; a piece of amber, glass, or a crystal rod; and three silver pins' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target. A target can be a creature or an object and can be targeted by only one of the bolts. A target must make a Dexterity saving throw. The target takes 10d8 lightning damage on a failed save, or half as much damage on a successful one.',
    higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, one additional bolt leaps from the first target to another target for each slot level above 6th.',
  },
  {
    id: 'disintegrate', name: 'Disintegrate', level: 6, school: 'Transmutation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: 'A lodestone and a pinch of dust' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'A thin green ray springs from your pointing finger to a target you can see within range. The target can be a creature, an object, or a creation of magical force, such as the wall created by wall of force. A creature targeted by this spell must make a Dexterity saving throw. On a failed save, the target takes 10d6 + 40 force damage. The target is disintegrated if this damage leaves it with 0 hit points.',
    higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, the damage increases by 3d6 for each slot level above 6th.',
  },
  {
    id: 'globe-of-invulnerability', name: 'Globe of Invulnerability', level: 6, school: 'Abjuration',
    castingTime: '1 Action', range: 'Self (10-foot radius)',
    components: { verbal: true, somatic: true, material: 'A glass or crystal bead that shatters when the spell ends' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'An immobile, faintly shimmering barrier springs into existence in a 10-foot radius around you and remains for the duration. Any spell of 5th level or lower cast from outside the barrier can\'t affect creatures or objects within it, even if the spell is cast using a higher level spell slot. Such a spell can target creatures and objects within the barrier, but the spell has no effect on them.',
    higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, the barrier blocks spells of one level higher for each slot level above 6th.',
  },
  {
    id: 'heal', name: 'Heal', level: 6, school: 'Evocation',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Choose a creature that you can see within range. A surge of positive energy washes through the creature, causing it to regain 70 hit points. This spell also ends blindness, deafness, and any diseases affecting the target. This spell has no effect on constructs or undead.',
    higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, the amount of healing increases by 10 for each slot level above 6th.',
  },
  {
    id: 'true-seeing', name: 'True Seeing', level: 6, school: 'Divination',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'An ointment for the eyes that costs 25 gp; is made from mushroom powder, saffron, and fat; and is consumed by the spell' },
    duration: '1 hour', concentration: false, ritual: false,
    description: 'You give the willing creature you touch the ability to see things as they actually are. For the duration, the creature has truesight, notices secret doors hidden by magic, and can see into the Ethereal Plane, all out to a range of 120 feet.',
    higherLevels: null,
  },
  {
    id: 'sunbeam', name: 'Sunbeam', level: 6, school: 'Evocation',
    castingTime: '1 Action', range: 'Self (60-foot line)',
    components: { verbal: true, somatic: true, material: 'A magnifying glass' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'A beam of brilliant light flashes out from your hand in a 5-foot-wide, 60-foot-long line. Each creature in the line must make a Constitution saving throw. On a failed save, a creature takes 6d8 radiant damage and is blinded until your next turn. On a successful save, it takes half as much damage and isn\'t blinded by this spell. Undead and oozes have disadvantage on this saving throw.',
    higherLevels: null,
  },

  // ── 7th Level ────────────────────────────────────────────────────────────────
  {
    id: 'finger-of-death', name: 'Finger of Death', level: 7, school: 'Necromancy',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You send negative energy coursing through a creature that you can see within range, causing it searing pain. The target must make a Constitution saving throw. It takes 7d8 + 30 necrotic damage on a failed save, or half as much damage on a successful one. A humanoid killed by this spell rises at the start of your next turn as a zombie that is permanently under your command, following your verbal orders to the best of its ability.',
    higherLevels: null,
  },
  {
    id: 'forcecage', name: 'Forcecage', level: 7, school: 'Evocation',
    castingTime: '1 Action', range: '100 feet',
    components: { verbal: true, somatic: true, material: 'Ruby dust worth 1,500 gp' },
    duration: '1 hour', concentration: false, ritual: false,
    description: 'An immobile, invisible, cube-shaped prison composed of magical force springs into existence around an area you choose within range. The prison can be a cage or a solid box as you choose. A prison in the shape of a cage can be up to 20 feet on a side and is made from 1/2-inch diameter bars spaced 1/2 inch apart. A prison in the shape of a box can be up to 10 feet on a side, creating a solid barrier that prevents any matter from passing through it.',
    higherLevels: null,
  },
  {
    id: 'plane-shift', name: 'Plane Shift', level: 7, school: 'Conjuration',
    castingTime: '1 Action', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'A forked, metal rod worth at least 250 gp, attuned to a specific plane of existence' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You and up to eight willing creatures who link hands in a circle are transported to a different plane of existence. You can specify a target destination in general terms, such as the City of Brass on the Elemental Plane of Fire or the palace of Dispater on the second level of the Nine Hells. Alternatively, if you use the spell as an attack, you can force a creature to make a Charisma saving throw. On a failed save, the creature is transported to a random location on the plane you specify.',
    higherLevels: null,
  },
  {
    id: 'teleport', name: 'Teleport', level: 7, school: 'Conjuration',
    castingTime: '1 Action', range: '10 feet',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'This spell instantly transports you and up to eight willing creatures of your choice that you can see within range, or a single object that you can see within range, to a destination you select. If you target an object, it must be able to fit entirely inside a 10-foot cube, and it can\'t be held or carried by an unwilling creature. The destination you choose must be known to you, and it must be on the same plane of existence as you.',
    higherLevels: null,
  },

  // ── 8th Level ────────────────────────────────────────────────────────────────
  {
    id: 'dominate-monster', name: 'Dominate Monster', level: 8, school: 'Enchantment',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: true, material: null },
    duration: 'Concentration, up to 1 hour', concentration: true, ritual: false,
    description: 'You attempt to beguile a creature that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. While the creature is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey.',
    higherLevels: null,
  },
  {
    id: 'earthquake', name: 'Earthquake', level: 8, school: 'Evocation',
    castingTime: '1 Action', range: '500 feet',
    components: { verbal: true, somatic: true, material: 'A pinch of dirt, a piece of rock, and a lump of clay' },
    duration: 'Concentration, up to 1 minute', concentration: true, ritual: false,
    description: 'You create a seismic disturbance at a point on the ground you can see within range. For the duration, an intense tremor rips through the ground in a 100-foot-radius circle centered on that point. Each creature on the ground in that area must make a Dexterity saving throw. On a failed save, the creature is knocked prone.',
    higherLevels: null,
  },
  {
    id: 'sunburst', name: 'Sunburst', level: 8, school: 'Evocation',
    castingTime: '1 Action', range: '150 feet',
    components: { verbal: true, somatic: true, material: 'Fire and a piece of sunstone' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Brilliant sunlight blazes in a 60-foot radius centered on a point you choose within range. Each creature in that light must make a Constitution saving throw. On a failed save, a creature takes 12d6 radiant damage and is blinded for 1 minute. On a successful save, it takes half as much damage and isn\'t blinded by this spell. Undead and oozes have disadvantage on this saving throw.',
    higherLevels: null,
  },

  // ── 9th Level ────────────────────────────────────────────────────────────────
  {
    id: 'power-word-kill', name: 'Power Word Kill', level: 9, school: 'Enchantment',
    castingTime: '1 Action', range: '60 feet',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You utter a word of power that can compel one creature you can see within range to die instantly. If the creature you choose has 100 hit points or fewer, it dies. Otherwise, the spell has no effect.',
    higherLevels: null,
  },
  {
    id: 'wish', name: 'Wish', level: 9, school: 'Conjuration',
    castingTime: '1 Action', range: 'Self',
    components: { verbal: true, somatic: false, material: null },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'Wish is the mightiest spell a mortal creature can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires. The basic use of this spell is to duplicate any other spell of 8th level or lower. You don\'t need to meet any requirements in that spell, including costly components. The spell simply takes effect. Alternatively, you can create one of the other effects described in the spell\'s full rules text. You might be able to achieve something beyond the scope of these examples.',
    higherLevels: null,
  },
  {
    id: 'true-resurrection', name: 'True Resurrection', level: 9, school: 'Necromancy',
    castingTime: '1 hour', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'A sprinkle of holy water and diamonds worth at least 25,000 gp, which the spell consumes' },
    duration: 'Instantaneous', concentration: false, ritual: false,
    description: 'You touch a creature that has been dead for no longer than 200 years and that died for any reason except old age. If the creature\'s soul is free and willing, the creature is restored to life with all its hit points. This spell closes all wounds, neutralizes any poison, cures all diseases, and lifts any curses affecting the creature when it died.',
    higherLevels: null,
  },
  {
    id: 'foresight', name: 'Foresight', level: 9, school: 'Divination',
    castingTime: '1 minute', range: 'Touch',
    components: { verbal: true, somatic: true, material: 'A hummingbird feather' },
    duration: '8 hours', concentration: false, ritual: false,
    description: 'You touch a willing creature and bestow a limited ability to see into the immediate future. For the duration, the target can\'t be surprised and has advantage on attack rolls, ability checks, and saving throws. Additionally, other creatures have disadvantage on attack rolls against the target for the duration. This spell immediately ends if you cast it again before its duration ends.',
    higherLevels: null,
  },
]
